services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peleja-api
    ports:
      - "${APP_PORT:-5000}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      NAuth__ApiURL: ${NAUTH_API_URL}
      NAuth__JwtSecret: ${JWT_SECRET}
      NAuth__BucketName: ${BUCKET_NAME}
      Tenants__emagine__ConnectionString: ${CONNECTION_STRING}
      Tenants__emagine__JwtSecret: ${JWT_SECRET}
      Tenants__emagine__BucketName: ${BUCKET_NAME}
      Tenants__peleja__ConnectionString: ${CONNECTION_STRING}
      Tenants__peleja__JwtSecret: ${JWT_SECRET}
      Tenants__peleja__BucketName: ${BUCKET_NAME}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - emagine-network

  db:
    image: postgres:17-alpine
    container_name: peleja-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - emagine-network

volumes:
  postgres_data:

networks:
  emagine-network:
    external: true
