services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peleja-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PelejaContext: ${CONNECTION_STRING}
      NAuth__ApiURL: ${NAUTH_API_URL}
      NAuth__JwtSecret: ${EMAGINE_JWT_SECRET}
      NAuth__BucketName: ${EMAGINE_BUCKET_NAME}
      Tenants__emagine__JwtSecret: ${EMAGINE_JWT_SECRET}
      Tenants__emagine__BucketName: ${EMAGINE_BUCKET_NAME}
      Tenants__peleja__JwtSecret: ${PELEJA_JWT_SECRET}
      Tenants__peleja__BucketName: ${PELEJA_BUCKET_NAME}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
    networks:
      - emagine-network

networks:
  emagine-network:
    external: true
